#!/usr/bin/with-contenv bash
# OurBlock Hub - Home Assistant Add-on Startup Script

set -e

# Source bashio library
# shellcheck disable=SC1091
source /usr/lib/bashio/bashio.sh

bashio::log.info "Starting OurBlock Hub..."

# Get configuration from Home Assistant
NEIGHBORHOOD_NAME=$(bashio::config 'neighborhood_name')
ADMIN_PASSWORD=$(bashio::config 'admin_password')
ENABLE_VOUCHING=$(bashio::config 'enable_vouching')
LOG_LEVEL=$(bashio::config 'log_level')

# Generate admin password if not provided
if [ -z "$ADMIN_PASSWORD" ]; then
    ADMIN_PASSWORD=$(openssl rand -base64 32)
    bashio::log.warning "Auto-generated admin password: $ADMIN_PASSWORD"
    bashio::log.warning "Save this password! You can change it in the add-on configuration."
fi

# Create .env file from configuration
cat > /app/.env <<EOF
# OurBlock Hub Configuration (Auto-generated by Home Assistant)
NEIGHBORHOOD_NAME=${NEIGHBORHOOD_NAME}
ADMIN_API_KEY=${ADMIN_PASSWORD}
ENABLE_VOUCHING=${ENABLE_VOUCHING}
RUST_LOG=${LOG_LEVEL}
APP_VERSION=0.1.0

# Network configuration (host network mode - direct port access)
MDNS_HOSTNAME=ourblock.local
CONDUCTOR_PORT=8888
UI_PORT=4443
HTTPS_PORT=4443
EOF

bashio::log.info "Configuration created for neighborhood: ${NEIGHBORHOOD_NAME}"

# Start mDNS discovery service
bashio::log.info "Starting mDNS discovery service..."
/app/discover.sh &

# Configure Docker socket from Home Assistant
export DOCKER_HOST="unix:///var/run/docker.sock"

# Wait for Docker daemon to be ready
bashio::log.info "Waiting for Docker daemon..."
timeout 30 sh -c 'until docker info > /dev/null 2>&1; do sleep 1; done' || {
  bashio::log.error "Docker daemon not accessible. Check add-on configuration."
  exit 1
}

# Build images if needed
if [ ! -f /app/.images_built ]; then
    bashio::log.info "Building Docker images (first run, this may take 10-15 minutes)..."
    cd /app
    docker compose build --no-cache
    touch /app/.images_built
    bashio::log.info "Images built successfully!"
fi

# Start services
bashio::log.info "Starting OurBlock Hub services..."
cd /app
docker compose up -d

# Wait for services to be healthy
bashio::log.info "Waiting for services to be ready..."
sleep 10

# Display service status
docker compose ps

bashio::log.info "OurBlock Hub is running!"
bashio::log.info "Access the UI at: https://ourblock.local:4443 or https://$(hostname -I | awk '{print $1}'):4443"
bashio::log.info "Mobile apps can connect to: ws://ourblock.local:8888"

if [ -z "$(bashio::config 'admin_password')" ]; then
  bashio::log.warning "═══════════════════════════════════════════════════════"
  bashio::log.warning "  AUTO-GENERATED ADMIN PASSWORD"
  bashio::log.warning "  ${ADMIN_PASSWORD}"
  bashio::log.warning "  Save this password and update in add-on configuration!"
  bashio::log.warning "═══════════════════════════════════════════════════════"
fi

# Keep the script running and forward logs
docker compose logs -f
