#!/bin/bash
# OurBlock Hub - Home Assistant Add-on Startup Script

set -e

ts() {
  date "+%Y-%m-%d %H:%M:%S"
}

log_info() {
  echo "[$(ts)] [info] $*"
}

log_warn() {
  echo "[$(ts)] [warn] $*"
}

log_error() {
  echo "[$(ts)] [error] $*"
}

config_get() {
  local key="$1"
  if [ -f /data/options.json ]; then
    jq -r --arg k "$key" '.[$k] // empty' /data/options.json
  else
    echo ""
  fi
}

log_info "Starting OurBlock Hub..."

# Get configuration from Home Assistant
NEIGHBORHOOD_NAME=$(config_get 'neighborhood_name')
ADMIN_PASSWORD=$(config_get 'admin_password')
ENABLE_VOUCHING=$(config_get 'enable_vouching')
LOG_LEVEL=$(config_get 'log_level')

NEIGHBORHOOD_NAME=${NEIGHBORHOOD_NAME:-"My Neighborhood"}
ENABLE_VOUCHING=${ENABLE_VOUCHING:-true}
LOG_LEVEL=${LOG_LEVEL:-info}

# Generate admin password if not provided
if [ -z "$ADMIN_PASSWORD" ]; then
  ADMIN_PASSWORD=$(openssl rand -base64 32)
  log_warn "Auto-generated admin password: $ADMIN_PASSWORD"
  log_warn "Save this password! You can change it in the add-on configuration."
fi

# Create .env file from configuration
cat > /app/.env <<EOF
# OurBlock Hub Configuration (Auto-generated by Home Assistant)
NEIGHBORHOOD_NAME=${NEIGHBORHOOD_NAME}
ADMIN_API_KEY=${ADMIN_PASSWORD}
ENABLE_VOUCHING=${ENABLE_VOUCHING}
RUST_LOG=${LOG_LEVEL}
APP_VERSION=0.1.0

# Network configuration (host network mode - direct port access)
MDNS_HOSTNAME=ourblock.local
CONDUCTOR_PORT=8888
UI_PORT=4443
HTTPS_PORT=4443
EOF

log_info "Configuration created for neighborhood: ${NEIGHBORHOOD_NAME}"

# Start mDNS discovery service
log_info "Starting mDNS discovery service..."
/app/discover.sh &

# Configure Docker access
DOCKER_SOCK=""
if [ -S /var/run/docker.sock ]; then
  DOCKER_SOCK="/var/run/docker.sock"
elif [ -S /run/docker.sock ]; then
  DOCKER_SOCK="/run/docker.sock"
fi

if [ -n "$DOCKER_SOCK" ]; then
  log_info "Using Docker socket: ${DOCKER_SOCK}"
  ls -la "${DOCKER_SOCK}" || true
  export DOCKER_HOST="unix://${DOCKER_SOCK}"
else
  log_warn "Docker socket not found. Trying supervisor Docker proxy..."
  export DOCKER_HOST="tcp://supervisor:2375"
  export DOCKER_TLS_VERIFY=0
fi

# Wait for Docker daemon to be ready
log_info "Waiting for Docker daemon..."
if ! timeout 30 sh -c 'until docker info > /dev/null 2>&1; do sleep 1; done'; then
  log_warn "Docker daemon not accessible. Attempting to start local dockerd..."
  mkdir -p /var/run
  dockerd --host=unix:///var/run/docker.sock > /var/log/dockerd.log 2>&1 &
  sleep 3
  if ! timeout 30 sh -c 'until docker info > /dev/null 2>&1; do sleep 1; done'; then
    log_error "Docker daemon still not accessible."
    log_error "Listing /var/run and /run for diagnostics:"
    ls -la /var/run || true
    ls -la /run || true
    log_error "Dockerd log (if any):"
    tail -n 200 /var/log/dockerd.log || true
    exit 1
  fi
fi

# Build images if needed
if [ ! -f /app/.images_built ]; then
    log_info "Building Docker images (first run, this may take 10-15 minutes)..."
    cd /app
    docker compose build --no-cache
    touch /app/.images_built
    log_info "Images built successfully!"
fi

# Start services
log_info "Starting OurBlock Hub services..."
cd /app
docker compose up -d

# Wait for services to be healthy
log_info "Waiting for services to be ready..."
sleep 10

# Display service status
docker compose ps

log_info "OurBlock Hub is running!"
log_info "Access the UI at: https://ourblock.local:4443 or https://$(hostname -I | awk '{print $1}'):4443"
log_info "Mobile apps can connect to: ws://ourblock.local:8888"

if [ -z "$(config_get 'admin_password')" ]; then
  log_warn "═══════════════════════════════════════════════════════"
  log_warn "  AUTO-GENERATED ADMIN PASSWORD"
  log_warn "  ${ADMIN_PASSWORD}"
  log_warn "  Save this password and update in add-on configuration!"
  log_warn "═══════════════════════════════════════════════════════"
fi

# Keep the script running and forward logs
docker compose logs -f
